name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  TOKEN: ${{ secrets.TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SA_KEY: ${{ secrets.SA_KEY }}
  REGION: us-central1
  IMAGE_NAME: image

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: $SA_KEY
          project_id: $PROJECT_ID

      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME:"latest

      - name: Deploy
        run: |-
          gcloud run deploy "$IMAGE_NAME" \
            --quiet \
            --region "$REGION" \
            --image "gcr.io/$PROJECT_ID/$IMAGE_NAME:latest" \
            --platform "managed" \
            --allow-unauthenticated
