name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  TOKEN: ${{ secrets.TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  IMAGE_NAME: image

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Setup
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $RUN_REGION

      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
            --platform managed \
            --allow-unauthenticated
